<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>9c866025-5f4d-47e6-8488-a6d1707a5cce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product']/div[2]/div/div[4]/div/div/div/div/div[9]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(9) > a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d42f96fc-2916-4637-bb56-f5f9834a4084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://staging.ezypolis.com:3003/images/others.png</value>
      <webElementGuid>f4508151-e25d-421f-ad5d-dff9b1c1244d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>40%</value>
      <webElementGuid>f78a2063-d501-44b6-8536-e6f68b440b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product&quot;)/div[@class=&quot;grid-padding text-center&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;card-block&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;d-flex flex-lg-row flex-xs-row flex-column align-items-center&quot;]/div[@class=&quot;flex-grow-1 text-lg-start text-center align-items-center&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-3 text-center text-white card-product&quot;]/a[1]/img[1]</value>
      <webElementGuid>013a6bd9-4387-403b-8ec9-8a8f7ad4c16b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product']/div[2]/div/div[4]/div/div/div/div/div[9]/a/img</value>
      <webElementGuid>05751a96-5646-4f7b-92e3-0b3b5c53beac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://staging.ezypolis.com:3003/images/others.png')])[2]</value>
      <webElementGuid>656f494b-f55d-448c-a9b2-9ff6af1938d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/a/img</value>
      <webElementGuid>26170cd1-c71f-4880-a603-4719fc9e705d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://staging.ezypolis.com:3003/images/others.png']</value>
      <webElementGuid>587fcbee-6136-4827-995a-8bfc97de5133</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
