<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Others</name>
   <tag></tag>
   <elementGuidId>9b5699f3-c03b-4c22-975d-7e11c991c9f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product']/div[2]/div/div[4]/div/div/div/div/div[9]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Others&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>001fc75c-c8c4-454e-9bb8-fadfe8494332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Others</value>
      <webElementGuid>4d618a8e-2eba-4f7b-ae08-8def6d7824c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product&quot;)/div[@class=&quot;grid-padding text-center&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;card-block&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;d-flex flex-lg-row flex-xs-row flex-column align-items-center&quot;]/div[@class=&quot;flex-grow-1 text-lg-start text-center align-items-center&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-3 text-center text-white card-product&quot;]/p[1]</value>
      <webElementGuid>1f8f4029-f76d-4c72-866e-fe40e60b36af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product']/div[2]/div/div[4]/div/div/div/div/div[9]/p</value>
      <webElementGuid>4e9d3134-3817-438c-ab4f-5d2f859c44af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Produk Asuransi'])[1]/following::p[9]</value>
      <webElementGuid>edcc1615-211b-44d1-a0fb-26744ca77671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Polis'])[1]/following::p[12]</value>
      <webElementGuid>390227e3-ab7f-4c6b-8a82-942d4ba03a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT MANGGALA ARTHA SEJAHTERA'])[1]/preceding::p[1]</value>
      <webElementGuid>6ea642e0-4323-451a-8831-9d63f7834eee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bantuan'])[2]/preceding::p[3]</value>
      <webElementGuid>e74efdbc-c760-488b-a6cf-198d24ec2f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Others']/parent::*</value>
      <webElementGuid>e1760361-f754-4b48-8bf9-a0ab32622444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/p</value>
      <webElementGuid>51341530-8d59-4618-b927-43b5aaf50416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Others' or . = 'Others')]</value>
      <webElementGuid>6202cf43-0ca2-4291-ac7d-50e41162f130</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
