<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__birthdate</name>
   <tag></tag>
   <elementGuidId>209b8a23-81b1-4c34-8ec9-96c8d3375786</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='birthdate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#birthdate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Tanggal Lahir *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>17dbc5a9-0ace-4bf3-9f42-a6a9bf69770b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-field_field-input__Z28kU !rounded-r-none</value>
      <webElementGuid>177dc59a-62cd-40e7-81cf-fd0e6fa0a1e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>birthdate</value>
      <webElementGuid>f806768c-fa1f-442b-8519-deb42496491f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>birthdate</value>
      <webElementGuid>5d969a03-d609-4a1c-8b98-065673a8946e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD/MM/YYYY</value>
      <webElementGuid>6bb74498-de36-45d5-a8f6-50781ba78130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;birthdate&quot;)</value>
      <webElementGuid>115b79eb-4076-441c-99ef-1936c020a321</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='birthdate']</value>
      <webElementGuid>3b68801e-7215-49ce-b846-afeed921083f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/section/div[2]/div/div/form/div[2]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>ccf57948-34fe-438b-9eba-063eb96cebce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div/input</value>
      <webElementGuid>2810d5bb-dba1-408f-9633-ed5012b12af3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'birthdate' and @name = 'birthdate' and @placeholder = 'DD/MM/YYYY']</value>
      <webElementGuid>158bf4b6-6436-456c-bc24-3e9ce724bc2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
