<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Terima Kasih. Pengajuan Asuransi Anda b_772255</name>
   <tag></tag>
   <elementGuidId>249018be-68a9-4ff0-a6cb-0028ff4f9a37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.Toastify__toast-body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='s2bopfoye']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Terima Kasih. Pengajuan Asuransi Anda berhasil. Silahkan cek email Anda&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e628bcc8-f220-42c5-99ea-7857ac5f581d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>afc3a417-a1b1-4175-b10e-83f779372533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Toastify__toast-body</value>
      <webElementGuid>f6b6abda-4ef9-44aa-9ae7-ae696d728375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terima Kasih. Pengajuan Asuransi Anda berhasil. Silahkan cek email Anda  </value>
      <webElementGuid>ce4f4f4f-7477-42d4-b9a4-a4db836f5ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;s2bopfoye&quot;)/div[@class=&quot;Toastify__toast-body&quot;]</value>
      <webElementGuid>b1d5a0c9-d74a-4946-aba0-6e5503130b72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='s2bopfoye']/div</value>
      <webElementGuid>94c6ef1f-7721-461e-b4e1-312d0da0f2f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim'])[1]/following::div[4]</value>
      <webElementGuid>6c8b1c73-9fe2-477f-86dc-83ace57debc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/following::div[4]</value>
      <webElementGuid>234e4946-64ac-4da5-be82-12483a3cc685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Footer'])[1]/preceding::div[2]</value>
      <webElementGuid>f17b1374-3387-416d-8a95-31eb44a9230c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT MANGGALA ARTHA SEJAHTERA'])[1]/preceding::div[4]</value>
      <webElementGuid>a1d41984-3fbe-4d2f-b348-8912c8062c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Terima Kasih. Pengajuan Asuransi Anda berhasil. Silahkan cek email Anda']/parent::*</value>
      <webElementGuid>c4314e78-e0f6-4939-ab97-0d393cd92cce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div</value>
      <webElementGuid>335f3098-69d7-4349-84cd-1e6f749ea015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Terima Kasih. Pengajuan Asuransi Anda berhasil. Silahkan cek email Anda  ' or . = 'Terima Kasih. Pengajuan Asuransi Anda berhasil. Silahkan cek email Anda  ')]</value>
      <webElementGuid>2efdba53-dc87-4446-afda-9e2fb6e790a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='s24ri8gdh']/div</value>
      <webElementGuid>c46433c8-085c-4d52-941f-f448b4d5a41d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
