<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>27af553e-618c-4773-8736-c8e0f0ce82e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-lg-3.text-center.text-white.card-product > a > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product']/div[2]/div/div[4]/div/div/div/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.col-lg-3 > a >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b0f09e05-b0dc-4401-b8e6-69d178cdeffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://staging.ezypolis.com:3003/images/personal-accident.png</value>
      <webElementGuid>d19712a0-11ab-4e8f-ba51-b2de548361f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>40%</value>
      <webElementGuid>2ab347ef-e563-4518-ab52-96485b6c12aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product&quot;)/div[@class=&quot;grid-padding text-center&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;card-block&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;d-flex flex-lg-row flex-xs-row flex-column align-items-center&quot;]/div[@class=&quot;flex-grow-1 text-lg-start text-center align-items-center&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-3 text-center text-white card-product&quot;]/a[1]/img[1]</value>
      <webElementGuid>f1fcce26-3d11-4db5-ada0-e18cd1965a5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product']/div[2]/div/div[4]/div/div/div/div/div/a/img</value>
      <webElementGuid>8bdfdeab-dcb5-4fdf-97d9-f39f090a3bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://staging.ezypolis.com:3003/images/personal-accident.png')]</value>
      <webElementGuid>8341a743-e102-4f50-b998-c69e749579c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a/img</value>
      <webElementGuid>47d2453b-c79a-42bb-aab4-732c23bf6d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://staging.ezypolis.com:3003/images/personal-accident.png']</value>
      <webElementGuid>870d73bd-70eb-4c9c-8d21-78968fe11877</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
