<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_img altAsuransi Kecelakaan Diri srcSet_ne_aae013</name>
   <tag></tag>
   <elementGuidId>ac7c9df8-2a1d-40da-b989-d371dad28684</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='section-product-recommendations']/div/div/div[2]/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Asuransi Kecelakaan Diri Asuransi Kecelakaan Diri&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>129af4e7-1720-45e7-8a0c-a03049ca5f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link_base-link__fSADh inline-flex flex-col items-center text-gray-2 p-4 rounded-xl transition duration-500 ease-in-out hover:shadow-sm hover:bg-white</value>
      <webElementGuid>9820541e-92b1-4ed5-935a-28770c434286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/insurance/personal-accident</value>
      <webElementGuid>e447fd05-1697-4549-8fd9-34edd8294553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;img alt=&quot;Asuransi Kecelakaan Diri&quot; srcSet=&quot;/_next/static/media/healthinsurance.92213351.svg 1x, /_next/static/media/healthinsurance.92213351.svg 2x&quot; src=&quot;/_next/static/media/healthinsurance.92213351.svg&quot; decoding=&quot;async&quot; data-nimg=&quot;intrinsic&quot; style=&quot;position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%&quot; loading=&quot;lazy&quot;/>Asuransi Kecelakaan Diri</value>
      <webElementGuid>d5333f8c-d6af-4248-8d45-2116acbed467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section-product-recommendations&quot;)/div[@class=&quot;px-4 sm:px-6 lg:px-8 xs:mt-96 md:mt-96&quot;]/div[@class=&quot;p-8 flex flex-col rounded-[45px] bg-brand-whitegray shadow-md&quot;]/div[@class=&quot;mt-6 w-full max-w-xl mx-auto grid grid-rows-3 sm:grid-rows-1 grid-cols-1 sm:grid-cols-2 gap-x-8 gap-y-5&quot;]/a[@class=&quot;link_base-link__fSADh inline-flex flex-col items-center text-gray-2 p-4 rounded-xl transition duration-500 ease-in-out hover:shadow-sm hover:bg-white&quot;]</value>
      <webElementGuid>1fc2de07-30a4-44a4-92b0-b2258080cc11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section-product-recommendations']/div/div/div[2]/a[3]</value>
      <webElementGuid>b55deff5-fb5b-4444-b914-fa5986f951d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asuransi Perjalanan'])[1]/following::a[1]</value>
      <webElementGuid>98c7ab4c-689f-4314-aee2-8cc296df9a67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roadside Assistance'])[1]/following::a[2]</value>
      <webElementGuid>aab1cc49-cf99-4404-917d-76988d9044d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asuransi Kendaraan'])[1]/preceding::a[1]</value>
      <webElementGuid>16aa6988-d383-44b3-b11b-899a033062c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/insurance/personal-accident')]</value>
      <webElementGuid>2223c1ee-d8b9-44e2-b5e2-9a03ecf82283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>64c9865a-1faf-4b28-8b39-2e0c875ac7b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/insurance/personal-accident' and (text() = '&lt;img alt=&quot;Asuransi Kecelakaan Diri&quot; srcSet=&quot;/_next/static/media/healthinsurance.92213351.svg 1x, /_next/static/media/healthinsurance.92213351.svg 2x&quot; src=&quot;/_next/static/media/healthinsurance.92213351.svg&quot; decoding=&quot;async&quot; data-nimg=&quot;intrinsic&quot; style=&quot;position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%&quot; loading=&quot;lazy&quot;/>Asuransi Kecelakaan Diri' or . = '&lt;img alt=&quot;Asuransi Kecelakaan Diri&quot; srcSet=&quot;/_next/static/media/healthinsurance.92213351.svg 1x, /_next/static/media/healthinsurance.92213351.svg 2x&quot; src=&quot;/_next/static/media/healthinsurance.92213351.svg&quot; decoding=&quot;async&quot; data-nimg=&quot;intrinsic&quot; style=&quot;position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%&quot; loading=&quot;lazy&quot;/>Asuransi Kecelakaan Diri')]</value>
      <webElementGuid>6165059b-a309-474c-ac28-53ccd2b6f106</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
