<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DI Yogyakarta</name>
   <tag></tag>
   <elementGuidId>dce65454-9c2f-44a7-bef5-e37d19bad45b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-province-option-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-province-option-4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;DI Yogyakarta&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>09f1b7de-d36f-4f9f-9236-9b7b904c9853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-select__option react-select__option--is-focused css-1n7v3ny-option</value>
      <webElementGuid>b64bc2d5-5ab3-421b-b77b-7c087132a2c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-province-option-4</value>
      <webElementGuid>81074bde-fcab-4949-a407-6438a5db5999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>839e3f3d-9557-4408-ad5c-7a4e7cdf59ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DI Yogyakarta</value>
      <webElementGuid>a6f17f80-c387-4c81-b4b3-c84035807e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-province-option-4&quot;)</value>
      <webElementGuid>ffb90af9-2861-4d72-b8e8-b0014203e5f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-province-option-4']</value>
      <webElementGuid>7f54bb09-6db3-42c5-8419-e43316d1e8ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking-form']/div/form/div[2]/div/div[8]/div/div/div[2]/div/div[5]</value>
      <webElementGuid>7812407a-d0e8-430a-bfaf-3490512d09a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bengkulu'])[1]/following::div[1]</value>
      <webElementGuid>e5fa23be-3227-4858-8afc-84a18f795922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Banten'])[1]/following::div[2]</value>
      <webElementGuid>44e7d902-353d-45b6-9976-12b02904bae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DKI Jakarta'])[1]/preceding::div[1]</value>
      <webElementGuid>6b0807eb-c097-4142-a2c0-dfd758d57ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gorontalo'])[1]/preceding::div[2]</value>
      <webElementGuid>34318873-a7e4-4dd5-8b30-e48f93fc760c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DI Yogyakarta']/parent::*</value>
      <webElementGuid>8aa85ce6-6ac8-4fe3-a5f2-cfe74b940521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div[5]</value>
      <webElementGuid>ca9a10a6-8ee0-41e6-a1cd-020c7fe7bffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-province-option-4' and (text() = 'DI Yogyakarta' or . = 'DI Yogyakarta')]</value>
      <webElementGuid>a3bfeb6a-abb9-4d62-8db7-faa915ca0b43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
