<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_75.000IDR</name>
   <tag></tag>
   <elementGuidId>3d2be4c9-3919-48dd-b4ab-f9a9d3449b2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/section/div[2]/div/div[2]/div[2]/div[2]/div/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;75.000 IDR&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>363b56bc-c6d9-4d52-84af-18adf7a6d391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-lg text-gray-2 font-bold break-all</value>
      <webElementGuid>ef5918d7-dfc6-4227-afb9-88dd98e37da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>75.000 IDR  </value>
      <webElementGuid>918fbc08-06be-48aa-9b88-77176b5b20af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen flex flex-col&quot;]/main[@class=&quot;min-h-[calc(100vh-58px)] overflow-x-hidden&quot;]/section[@class=&quot;w-full h-full flex flex-col max-w-8xl mx-auto px-4 sm:px-6 lg:px-8 py-15&quot;]/div[@class=&quot;mt-10 flex flex-col lg:flex-row&quot;]/div[@class=&quot;w-full max-w-5xl mx-auto bg-brand-ivory rounded px-5 sm:px-9.5 py-7 sm:py-10 space-y-5&quot;]/div[@class=&quot;w-full px-5 bg-white rounded&quot;]/div[@class=&quot;md md:grid md:grid-cols-4 md:grid-flow-row md:gap-x-6.5&quot;]/div[@class=&quot;-my-2.5 -mx-5 py-5 md:col-span-3 flex flex-wrap&quot;]/div[@class=&quot;py-2.5 px-5 sm:w-1/2 xl:w-1/3 flex flex-col&quot;]/h4[@class=&quot;text-lg text-gray-2 font-bold break-all&quot;]</value>
      <webElementGuid>9a2673f6-d1be-44ea-8a35-05fdc6c831d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/section/div[2]/div/div[2]/div[2]/div[2]/div/h4</value>
      <webElementGuid>96cd67a5-9194-4ad6-af5d-f35e01416491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proteksi Bronze'])[1]/following::h4[1]</value>
      <webElementGuid>993a9254-4fd6-4230-bc30-d4b1d327bd4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selanjutnya'])[2]/following::h4[2]</value>
      <webElementGuid>589753a9-d457-471e-89a9-74efe3c1f65b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDR'])[6]/preceding::h4[1]</value>
      <webElementGuid>a187098f-039d-4f14-91e8-6b50855ab733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='75.000']/parent::*</value>
      <webElementGuid>63f287ab-3456-4d72-b386-6b61c19ce8cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/h4</value>
      <webElementGuid>04d961a2-4b39-4ab1-a445-2742ece4a1be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = '75.000 IDR  ' or . = '75.000 IDR  ')]</value>
      <webElementGuid>d84263c9-7551-4160-8f59-0c72455c8dbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
