<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Syarat dan Ketentuan_popup_1713947298114</name>
   <tag></tag>
   <elementGuidId>7e6d66ee-1a4b-4364-9601-104fa4266033</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#snap-midtrans</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='snap-midtrans']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;popup_1714065846522&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>272b0a03-ed2b-481b-b18a-e0b18f7382be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://app.sandbox.midtrans.com/snap/v4/popup?origin_host=https://staging.ezypolis.com:3001&amp;client_key=SB-Mid-client-3ypF2yRS05oytfet#/</value>
      <webElementGuid>46c97c7e-0e2a-49a5-b83b-6310267e5bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>snap-midtrans</value>
      <webElementGuid>fb8917d8-2e1a-472c-8db5-8f9b311a29fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>popup_1714065846522</value>
      <webElementGuid>917fe75e-c498-45e3-bdf1-b20db8b1f3d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;snap-midtrans&quot;)</value>
      <webElementGuid>6243c84b-f87c-4032-9788-3c8e40c6e3ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='snap-midtrans']</value>
      <webElementGuid>70b737d2-1c48-4372-9cca-22eeb93f3f98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>173fa26e-be57-4b3d-ac98-5bfc64283c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://app.sandbox.midtrans.com/snap/v4/popup?origin_host=https://staging.ezypolis.com:3001&amp;client_key=SB-Mid-client-3ypF2yRS05oytfet#/' and @id = 'snap-midtrans' and @name = 'popup_1714065846522']</value>
      <webElementGuid>ac49f01f-1de4-4ea3-a170-f497905f5b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://app.sandbox.midtrans.com/snap/v4/popup?origin_host=https://staging.ezypolis.com:3001&amp;client_key=SB-Mid-client-3ypF2yRS05oytfet#/' and @id = 'snap-midtrans' and @name = 'popup_1713949209783']</value>
      <webElementGuid>1a21fbbf-21f0-4d39-8696-16425c7282b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://app.sandbox.midtrans.com/snap/v4/popup?origin_host=https://staging.ezypolis.com:3001&amp;client_key=SB-Mid-client-3ypF2yRS05oytfet#/' and @id = 'snap-midtrans' and @name = 'popup_1713948345256']</value>
      <webElementGuid>e9b0ce0b-d7ba-4a5a-a2c7-bfc7ecdbe8a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://app.sandbox.midtrans.com/snap/v4/popup?origin_host=https://staging.ezypolis.com:3001&amp;client_key=SB-Mid-client-3ypF2yRS05oytfet#/' and @id = 'snap-midtrans' and @name = 'popup_1713947298114']</value>
      <webElementGuid>40d4034a-97bb-4e0b-8f17-7228c6dc590a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
