<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Syarat dan Ketentuan_popup_1713947298114</name>
   <tag></tag>
   <elementGuidId>7e6d66ee-1a4b-4364-9601-104fa4266033</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#snap-midtrans</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='snap-midtrans']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;popup_1715337461190&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e9b6c645-7899-4e7a-bf4d-b980ade72866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://app.sandbox.midtrans.com/snap/v4/popup?origin_host=https://staging.ezypolis.com:3001&amp;client_key=SB-Mid-client-3ypF2yRS05oytfet#/</value>
      <webElementGuid>deded4b0-bd11-4fe4-9bc5-6c39ce1b46fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>snap-midtrans</value>
      <webElementGuid>3a471e0f-da56-46e2-b91c-0e9be8ab9ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>popup_1715337461190</value>
      <webElementGuid>e72d93ea-bfbe-4976-ad43-d99b36460cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;snap-midtrans&quot;)</value>
      <webElementGuid>7aae0a2e-6903-4cbf-96da-0a5dba160674</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='snap-midtrans']</value>
      <webElementGuid>f3491b3d-0c18-480b-8554-f425e07e6a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>f3926d8f-2b92-41ce-a4a6-2d13cd579602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://app.sandbox.midtrans.com/snap/v4/popup?origin_host=https://staging.ezypolis.com:3001&amp;client_key=SB-Mid-client-3ypF2yRS05oytfet#/' and @id = 'snap-midtrans' and @name = 'popup_1715337461190']</value>
      <webElementGuid>4dae75af-9caf-4425-9bfb-be0a712095f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://app.sandbox.midtrans.com/snap/v4/popup?origin_host=https://staging.ezypolis.com:3001&amp;client_key=SB-Mid-client-3ypF2yRS05oytfet#/' and @id = 'snap-midtrans' and @name = 'popup_1715255089807']</value>
      <webElementGuid>b8a7f16f-d885-4a60-8866-c6eace130633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://app.sandbox.midtrans.com/snap/v4/popup?origin_host=https://staging.ezypolis.com:3001&amp;client_key=SB-Mid-client-3ypF2yRS05oytfet#/' and @id = 'snap-midtrans' and @name = 'popup_1714565545387']</value>
      <webElementGuid>8e5dbaf2-eb2e-41db-8855-b3ee84973548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://app.sandbox.midtrans.com/snap/v4/popup?origin_host=https://staging.ezypolis.com:3001&amp;client_key=SB-Mid-client-3ypF2yRS05oytfet#/' and @id = 'snap-midtrans' and @name = 'popup_1714065846522']</value>
      <webElementGuid>ac49f01f-1de4-4ea3-a170-f497905f5b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://app.sandbox.midtrans.com/snap/v4/popup?origin_host=https://staging.ezypolis.com:3001&amp;client_key=SB-Mid-client-3ypF2yRS05oytfet#/' and @id = 'snap-midtrans' and @name = 'popup_1713949209783']</value>
      <webElementGuid>1a21fbbf-21f0-4d39-8696-16425c7282b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://app.sandbox.midtrans.com/snap/v4/popup?origin_host=https://staging.ezypolis.com:3001&amp;client_key=SB-Mid-client-3ypF2yRS05oytfet#/' and @id = 'snap-midtrans' and @name = 'popup_1713948345256']</value>
      <webElementGuid>e9b0ce0b-d7ba-4a5a-a2c7-bfc7ecdbe8a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://app.sandbox.midtrans.com/snap/v4/popup?origin_host=https://staging.ezypolis.com:3001&amp;client_key=SB-Mid-client-3ypF2yRS05oytfet#/' and @id = 'snap-midtrans' and @name = 'popup_1713947298114']</value>
      <webElementGuid>40d4034a-97bb-4e0b-8f17-7228c6dc590a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
