<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__user_birth_place</name>
   <tag></tag>
   <elementGuidId>c71d39eb-d342-414e-8727-0394591e6120</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_birth_place</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_birth_place']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Contoh: Jakarta&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0474772-7dc5-4b14-824a-8465da05bea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_birth_place</value>
      <webElementGuid>d6ac53dc-ed8b-431c-a03e-8645acd37539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d4bdf50d-efbd-4604-beb6-d55f3a2b990e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_birth_place</value>
      <webElementGuid>c5b79f06-8bfd-4eff-ab0a-7663a8ad5e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: Jakarta</value>
      <webElementGuid>13430be2-418b-4723-877b-b8ea83234b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-field_field-input__Z28kU</value>
      <webElementGuid>7f07a00a-3773-4f0b-8a8d-699d9c2998fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_birth_place&quot;)</value>
      <webElementGuid>d28aa7ba-392d-443d-b713-7db28fab3201</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_birth_place']</value>
      <webElementGuid>9f155cfd-b10e-4c49-9177-1d632bcfadf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking-form']/div/form/div[2]/div/div[3]/div/input</value>
      <webElementGuid>4a56d87e-a7cf-44a8-95cb-2511a1458063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>751d7057-134d-4d8c-89fd-fb6d3bcdab13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'user_birth_place' and @type = 'text' and @name = 'user_birth_place' and @placeholder = 'Contoh: Jakarta']</value>
      <webElementGuid>77114048-3cad-45bb-880a-d52dd0913f98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
