<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__user_address</name>
   <tag></tag>
   <elementGuidId>a3a53b83-4b12-4d37-bde1-0ae8d2905036</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_address</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Contoh: Jl Kenangan no. 1&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dcc7aa2c-8caa-4c58-9c04-69e0fc67e959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_address</value>
      <webElementGuid>d1eda676-0272-42c3-bee7-6a8301d3c64e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>03f6e61a-7715-4724-956c-891395b5dd09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_address</value>
      <webElementGuid>9ea29f27-e7ab-44bd-aa2f-688669541fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: Jl Kenangan no. 1</value>
      <webElementGuid>5c477dd0-b340-45a7-a7ca-3a0909b407f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-field_field-input__Z28kU</value>
      <webElementGuid>b1e3e2f7-fc64-4306-8307-a5fd5b55d4d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_address&quot;)</value>
      <webElementGuid>d4660315-516f-4b75-bd99-f1162cb37f8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_address']</value>
      <webElementGuid>081b91d2-8001-4b3e-b5bf-e72242b71066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking-form']/div/form/div[2]/div/div[7]/div/input</value>
      <webElementGuid>d26dab05-9229-4fe7-b8ce-9ca36d1ffb3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>dde6767c-25b4-4aac-8561-f791dafe7b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'user_address' and @type = 'text' and @name = 'user_address' and @placeholder = 'Contoh: Jl Kenangan no. 1']</value>
      <webElementGuid>1765f85d-822e-454b-8b72-c905ca3d79db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
