<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__hometown</name>
   <tag></tag>
   <elementGuidId>6e0a1d81-b6dd-44ff-b470-5f7ffe2b2371</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hometown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='hometown']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Contoh: Balikpapan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6cb58563-ed20-4a2a-8d25-717153eff56f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hometown</value>
      <webElementGuid>e111553a-ab21-4e05-ae2b-5bf737b27e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>74e3b5e6-48d6-4d08-aa50-5da7acba0ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hometown</value>
      <webElementGuid>2fd7de64-bbd3-4351-b874-4942d35245d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: Balikpapan</value>
      <webElementGuid>bbd77b4d-ee72-4a41-81b0-f5ee87ecdee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-field_field-input__Z28kU</value>
      <webElementGuid>70e4408c-1509-460b-bcb2-7c921b669eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>T</value>
      <webElementGuid>ceeb3223-d32f-4b07-939d-10d009c40db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hometown&quot;)</value>
      <webElementGuid>baf55a01-97af-44c3-89a6-f03327627617</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='hometown']</value>
      <webElementGuid>51314314-cfc8-451a-b4b3-56447e52f994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/section/div[2]/div/div/div/div[3]/div/div/input</value>
      <webElementGuid>14a77d8f-82de-4924-8e93-ddc99e95661a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>f9a56e76-3792-44be-8199-26ddfd4e92b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'hometown' and @type = 'text' and @name = 'hometown' and @placeholder = 'Contoh: Balikpapan']</value>
      <webElementGuid>363dfb03-3a07-4014-b20e-59518da64f25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
