<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_75.000IDR</name>
   <tag></tag>
   <elementGuidId>18d36659-f913-40bf-b178-d5f6ada94c9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.text-sm.text-right.text-gray-2.font-bold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='booking-form']/div[2]/div/div[3]/div/p[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;75.000IDR&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>658d2eca-5ffb-45f0-9202-17e18f786ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm text-right text-gray-2 font-bold</value>
      <webElementGuid>f104d624-0dce-44ae-98f6-36421bd933dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>75.000IDR</value>
      <webElementGuid>bcd3928f-07fb-47ad-9302-804842320af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;booking-form&quot;)/div[@class=&quot;ml-10 w-full max-w-[357px]&quot;]/div[@class=&quot;bg-white w-full rounded-t overflow-hidden&quot;]/div[@class=&quot;mx-3 mb-3 py-3.5 bg-brand-ivory&quot;]/div[@class=&quot;-mx-3 px-5 flex justify-between space-x-5&quot;]/p[@class=&quot;text-sm text-right text-gray-2 font-bold&quot;]</value>
      <webElementGuid>393882a5-b110-4739-b844-8723a8577221</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking-form']/div[2]/div/div[3]/div/p[2]</value>
      <webElementGuid>ff162b80-c2b7-4a02-a7f7-192e7b2461b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Polis Selesai'])[1]/following::p[2]</value>
      <webElementGuid>d59a2ca4-7ae6-4e70-add6-f44dabc45bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Polis Mulai Aktif'])[1]/following::p[2]</value>
      <webElementGuid>fb59eb0a-3f39-432d-a369-3e8e3838d512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Footer'])[1]/preceding::p[1]</value>
      <webElementGuid>5b814b0b-7c46-48fc-8e1b-e1a86363b25f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='75.000']/parent::*</value>
      <webElementGuid>3ea92162-0875-4484-a40a-679a97a3d097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>8fde06db-45c2-4c13-ab11-15a49b60eac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '75.000IDR' or . = '75.000IDR')]</value>
      <webElementGuid>0ab5fcf1-c03b-42d8-9448-65c8383c8edb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
