<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>19f45e7a-e8f0-434d-b6e7-160b4e9c45f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product']/div[2]/div/div[4]/div/div/div/div/div[5]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(5) > a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>01082d1f-2bde-4e7d-8651-98e214357611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://staging.ezypolis.com:3003/images/property.png</value>
      <webElementGuid>bcff7010-48ad-4706-9ba9-f77e89e8d156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>40%</value>
      <webElementGuid>278530da-ee4f-49d9-8da4-820facab8933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product&quot;)/div[@class=&quot;grid-padding text-center&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;card-block&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;d-flex flex-lg-row flex-xs-row flex-column align-items-center&quot;]/div[@class=&quot;flex-grow-1 text-lg-start text-center align-items-center&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-3 text-center text-white card-product&quot;]/a[1]/img[1]</value>
      <webElementGuid>9446a9b1-6007-4a00-b67d-de550acb92fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product']/div[2]/div/div[4]/div/div/div/div/div[5]/a/img</value>
      <webElementGuid>1a5ecefe-58b3-4d59-bcff-9a7f24b5bdd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://staging.ezypolis.com:3003/images/property.png')]</value>
      <webElementGuid>c4218a35-e154-470b-9943-87dbf107433f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a/img</value>
      <webElementGuid>f78d6678-9705-401e-afb0-1022bad9cabb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://staging.ezypolis.com:3003/images/property.png']</value>
      <webElementGuid>98e20e67-fc82-4eb2-abe3-7c92136e1360</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
