<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>49d8148f-dd23-4026-bb6f-34f166337ba4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product']/div[2]/div/div[4]/div/div/div/div/div[2]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.row > div:nth-child(2) > a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d77dc072-d9a8-45b9-976e-0341745689f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://staging.ezypolis.com:3003/images/Travel.png</value>
      <webElementGuid>57846ec8-8fe1-461c-a523-a89e086160ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>40%</value>
      <webElementGuid>e17d33b4-dbcb-4b9f-836d-e2e43059768f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product&quot;)/div[@class=&quot;grid-padding text-center&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;card-block&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;d-flex flex-lg-row flex-xs-row flex-column align-items-center&quot;]/div[@class=&quot;flex-grow-1 text-lg-start text-center align-items-center&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-3 text-center text-white card-product&quot;]/a[1]/img[1]</value>
      <webElementGuid>76351172-7823-49ba-be67-111b895114f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product']/div[2]/div/div[4]/div/div/div/div/div[2]/a/img</value>
      <webElementGuid>7391e4cc-fb29-4bec-af66-928ee425648e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://staging.ezypolis.com:3003/images/Travel.png')]</value>
      <webElementGuid>bf157843-b20e-4482-8eb3-e644517724e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/img</value>
      <webElementGuid>3fa640d6-d92b-400b-adb6-87136719c841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://staging.ezypolis.com:3003/images/Travel.png']</value>
      <webElementGuid>64c34ed9-d795-4710-b3e9-5e8b89d81ab2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
