<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lihat Daftar Polis</name>
   <tag></tag>
   <elementGuidId>4c96c3b6-e129-4893-966b-2beb488ed5d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.button_btn__6yNqf.button_btn--solid-primary__1YfXJ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/section/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Lihat Daftar Polis&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3cafdc5f-ff8e-4792-8358-68e6f8a8bec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button_btn__6yNqf button_btn--solid-primary__1YfXJ</value>
      <webElementGuid>1485f651-454a-4ee3-82a2-1362ef45cd10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/302/insurances</value>
      <webElementGuid>e5068a1b-bfd3-4cdf-8ca3-c36c25d4baf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lihat Daftar Polis</value>
      <webElementGuid>60d98ced-bc58-4c41-b665-4d3dffc69e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen flex flex-col&quot;]/main[@class=&quot;min-h-[calc(100vh-58px)] overflow-x-hidden&quot;]/section[@class=&quot;w-full h-full flex flex-col max-w-8xl mx-auto px-4 sm:px-6 lg:px-8 py-15&quot;]/div[@class=&quot;mt-10 flex flex-col items-center&quot;]/div[@class=&quot;mt-10 inline-flex&quot;]/a[@class=&quot;button_btn__6yNqf button_btn--solid-primary__1YfXJ&quot;]</value>
      <webElementGuid>b6af9663-1189-4637-aca7-7fffccaf967e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/section/div[2]/div/a</value>
      <webElementGuid>84a21a63-c224-4fec-83be-fbbbdb48bca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Polis berhasil dibuat!'])[1]/following::a[1]</value>
      <webElementGuid>5bc35a22-b123-4732-b80a-9b558ba457ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sena pahlevi'])[1]/following::a[1]</value>
      <webElementGuid>8f39c976-7dfe-4a82-ae26-8f08435e59d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Footer'])[1]/preceding::a[1]</value>
      <webElementGuid>857e523c-efbd-4e6a-98ed-a1205c3ee67f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/302/insurances')]</value>
      <webElementGuid>cb6c4be8-fc37-48a4-9fe7-f12cbde3a76c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>fd6815cf-74ba-4fae-9bbe-28e4afe3d26b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/302/insurances' and (text() = 'Lihat Daftar Polis' or . = 'Lihat Daftar Polis')]</value>
      <webElementGuid>3829cfcd-773e-4f2e-b094-60071ad84590</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
