<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ALL NEW CHEVROLET TRAX LT 1.4 AT</name>
   <tag></tag>
   <elementGuidId>86967906-1dd3-48f4-8054-e6e5a2d22d80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-35-option-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-35-option-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;ALL NEW CHEVROLET TRAX LT 1.4 A/T&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1b28196f-c964-4969-88a5-bded653ff4b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-select__option react-select__option--is-focused css-1n7v3ny-option</value>
      <webElementGuid>4c0a5a13-c709-413c-9167-f4c5a1270bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-35-option-0</value>
      <webElementGuid>aed6d240-4f83-482b-89ff-5336256e5eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d79e639f-1eb6-435e-bc2f-506f2485a1ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ALL NEW CHEVROLET TRAX LT 1.4 A/T</value>
      <webElementGuid>7a12cb18-1c14-4853-b120-3afdc60a910d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-35-option-0&quot;)</value>
      <webElementGuid>40d3268d-80b5-46e4-a05e-805f61467500</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-35-option-0']</value>
      <webElementGuid>24c18e74-cbf6-47a4-84fd-6e507e4a34f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/section/div[2]/div[3]/div/div[4]/div/div/div/div[2]/div/div</value>
      <webElementGuid>39eb5c9d-ef14-4032-9501-8a55c2291586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--- Pilih ---'])[1]/following::div[5]</value>
      <webElementGuid>334cda17-d90d-4c62-8959-775d3fde0035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALL NEW CHEVROLET TRAX LTZ 1.4 A/T'])[1]/preceding::div[1]</value>
      <webElementGuid>a5a3f6b4-99c6-41a8-bc77-3ba31a79ff46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALL NEW CHEVROLET TRAX PREMIER 1.4 A/T'])[1]/preceding::div[2]</value>
      <webElementGuid>0d785278-19e1-445a-acc0-254899662562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ALL NEW CHEVROLET TRAX LT 1.4 A/T']/parent::*</value>
      <webElementGuid>1c2e7d6f-4bf9-4994-b3e6-ecdfdd827c18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div/div</value>
      <webElementGuid>71a0cef7-90c6-4709-9ed3-8bcd494aff86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-35-option-0' and (text() = 'ALL NEW CHEVROLET TRAX LT 1.4 A/T' or . = 'ALL NEW CHEVROLET TRAX LT 1.4 A/T')]</value>
      <webElementGuid>d2333db4-8f05-4156-b37d-01da8f05c8ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
