<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BASTK_absolute inset-0 bg-black bg-opac_e351cc</name>
   <tag></tag>
   <elementGuidId>b63b35ce-18f3-4b8a-8f71-05dc690f0331</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/section/div[2]/div[3]/div/div[3]/button/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;BASTK *&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b0dc7639-16c3-4a83-b796-770e3cab6882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute inset-0 bg-black bg-opacity-0 transition-colors group-hover:bg-opacity-50</value>
      <webElementGuid>15f047aa-be2e-4494-a25a-64c05cda49fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen flex flex-col&quot;]/main[@class=&quot;min-h-[calc(100vh-58px)] overflow-x-hidden&quot;]/section[@class=&quot;w-full h-full flex flex-col max-w-8xl mx-auto px-4 sm:px-6 lg:px-8 py-15&quot;]/div[@class=&quot;mt-10 w-full max-w-3xl mx-auto&quot;]/div[@class=&quot;mt-10&quot;]/div[@class=&quot;grid grid-cols-4 gap-4&quot;]/div[3]/button[@class=&quot;relative px-0 w-full h-full bg-gray-4 outline-black rounded-lg overflow-hidden text-1xl text-white font-bold group focus:outline-none focus:ring-2 focus:ring-brand-highlight&quot;]/div[@class=&quot;absolute inset-0 bg-black bg-opacity-0 transition-colors group-hover:bg-opacity-50&quot;]</value>
      <webElementGuid>b7b88294-d1e3-48ea-a1d1-44146c8e802f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/section/div[2]/div[3]/div/div[3]/button/div</value>
      <webElementGuid>cc77833a-b74e-486a-ab6b-f42b0f008758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/div</value>
      <webElementGuid>9f610f33-e8fe-4247-ab75-fc5414e82f21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
