<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Kota Jakarta Barat</name>
   <tag></tag>
   <elementGuidId>07eb2561-f84d-4530-a0ae-2c38155ff20a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-cities-option-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-cities-option-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Kota Jakarta Barat&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>78cda310-4691-4ac4-8a9d-b91cc1f9481b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-select__option react-select__option--is-focused css-1n7v3ny-option</value>
      <webElementGuid>d3ecb22e-843a-4966-968f-c63b8ab48a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-cities-option-1</value>
      <webElementGuid>5b0fffe0-192e-45b5-ae69-2cabae957ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>7f105920-d6e8-45bf-8379-6284289a0c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kota Jakarta Barat</value>
      <webElementGuid>6dd8b4da-d91e-4465-a12a-b8a8e2595154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-cities-option-1&quot;)</value>
      <webElementGuid>3bfcdd43-0f61-4ea5-a2af-6092a94b55f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-cities-option-1']</value>
      <webElementGuid>89529eb3-a3be-409a-ac88-a65d21e7ae07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking-form']/div/form/div[2]/div/div[9]/div/div/div[2]/div/div[2]</value>
      <webElementGuid>18880139-4d7b-4f91-8f5b-be0ffebf2d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kab. Kepulauan Seribu'])[1]/following::div[1]</value>
      <webElementGuid>321c33d5-26c1-43cb-9208-907abb0904e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Kota'])[1]/following::div[9]</value>
      <webElementGuid>88a38005-cdf8-4a67-982d-df5571347bd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kota Jakarta Pusat'])[1]/preceding::div[1]</value>
      <webElementGuid>d484ce81-c8e8-4d58-8cf1-387a0dcefc32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kota Jakarta Selatan'])[1]/preceding::div[2]</value>
      <webElementGuid>ebcdac8d-9871-4545-98b5-bdf03967808c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kota Jakarta Barat']/parent::*</value>
      <webElementGuid>2467389e-464c-4400-af17-ed084eca99e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div[2]</value>
      <webElementGuid>936a87e2-6ecf-43d7-a19b-97b3f2adbe6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-cities-option-1' and (text() = 'Kota Jakarta Barat' or . = 'Kota Jakarta Barat')]</value>
      <webElementGuid>6a9cfa08-731c-4fe7-bc70-1d04e5223e5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
