<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nomor Teleponminimal 10 digitEmail User_d59a72</name>
   <tag></tag>
   <elementGuidId>a4801360-d834-438d-a25a-746163a170c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.motor-vehicle_popupcontent__4_e9q</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/section/div[2]/div[3]/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Nomor Telepon **minimal 10 digitEmail User *Selanjutnya&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8a36d2e9-05d4-4fc6-b2a0-4149c9389a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>motor-vehicle_popupcontent__4_e9q</value>
      <webElementGuid>abc92e94-db9c-4e37-be8d-22cd9a5aa1e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nomor Telepon **minimal 10 digitEmail User *Selanjutnya</value>
      <webElementGuid>109e3669-7aed-4adf-94d2-2187d3664d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen flex flex-col&quot;]/main[@class=&quot;min-h-[calc(100vh-58px)] overflow-x-hidden&quot;]/section[@class=&quot;w-full h-full flex flex-col max-w-8xl mx-auto px-4 sm:px-6 lg:px-8 py-15&quot;]/div[@class=&quot;mt-10 w-full max-w-3xl mx-auto&quot;]/div[@class=&quot;mt-10&quot;]/div[@class=&quot;relative w-full max-w-xs mx-auto&quot;]/div[@class=&quot;motor-vehicle_popup__jmapq&quot;]/div[@class=&quot;motor-vehicle_popupbody__Z52gC&quot;]/div[@class=&quot;motor-vehicle_popupcontent__4_e9q&quot;]</value>
      <webElementGuid>e3bf99ad-3099-4ef9-9352-dc98d5b12f25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/section/div[2]/div[3]/div/div[2]/div/div</value>
      <webElementGuid>2a65318e-4f74-405e-ab37-1f1d28ab9646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cek rangka'])[1]/following::div[3]</value>
      <webElementGuid>05f61909-aeda-4845-91ac-07e5a459b5f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div</value>
      <webElementGuid>f31efd8e-ee41-499b-a9dd-b3123a4750e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Nomor Telepon **minimal 10 digitEmail User *Selanjutnya' or . = 'Nomor Telepon **minimal 10 digitEmail User *Selanjutnya')]</value>
      <webElementGuid>9ffbe1e5-24cc-4aac-8be6-9ac1c4b05ed9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
