<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Virtual account_bank-list-content</name>
   <tag></tag>
   <elementGuidId>037138e6-ee42-4610-9075-802ae8932945</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.bank-list-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='application']/div/div/div[3]/div/div/div[2]/div/a/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;banklogo&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>08a51f41-a9a8-4466-be82-34ed7d2d703f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bank-list-content</value>
      <webElementGuid>dce2db9c-eec4-46f7-a79f-aca1535fb466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application&quot;)/div[@class=&quot;page-container scroll&quot;]/div[@class=&quot;payment-container-list&quot;]/div[3]/div[@class=&quot;collapsible-payment&quot;]/div[@class=&quot;collapsible collapsible-payment--multiple&quot;]/div[@class=&quot;content collapsible-payment--multiple opened&quot;]/div[@class=&quot;bank-list-layout horizontal&quot;]/a[@class=&quot;bank-list&quot;]/div[@class=&quot;payment-page-text horizontal&quot;]/div[@class=&quot;bank-list-content&quot;]</value>
      <webElementGuid>93a8a51e-11c5-48eb-ae68-deae0b3c345a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Motor Vehicle/MV - Journey Purchase/iframe_concat(id(, , snap-midtrans, , ))_po_696993</value>
      <webElementGuid>243a144c-ef4d-449d-b114-b565e8d4e143</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application']/div/div/div[3]/div/div/div[2]/div/a/div/div</value>
      <webElementGuid>2e035bd9-2ddb-4642-971d-1f0af25fef5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Virtual account'])[1]/following::div[10]</value>
      <webElementGuid>f48cb0b0-9022-4c02-83f4-c9bf4847ec54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kartu kredit/debit'])[1]/following::div[23]</value>
      <webElementGuid>f5155d49-f213-4556-a62e-b69b56ebcbaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank lainnya'])[1]/preceding::div[11]</value>
      <webElementGuid>ea752bd5-1f71-49ed-bfca-42b5fef00f7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KlikBCA'])[1]/preceding::div[15]</value>
      <webElementGuid>d803097d-2a84-45bd-bb3a-8267bb3defc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/div/div</value>
      <webElementGuid>970b60c7-6b47-4c33-8324-c7a61e5597fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
