<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>c0f08925-a1e7-46fa-a45c-1f14c3498288</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Asuransi Kendaraan&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='section-product-recommendations']/div/div/div[2]/a[4]/div/div/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Asuransi Kendaraan Asuransi Kendaraan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dfcfd10c-99c4-4339-999d-982849283fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Asuransi Kendaraan</value>
      <webElementGuid>d47df135-d566-417b-890b-8c03beec0ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/static/media/carinsurance.c2dadb4c.svg</value>
      <webElementGuid>0d87e7eb-2879-4e93-94e2-63988e940ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>d0912001-9138-47bd-9d63-d0f9518a54d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>intrinsic</value>
      <webElementGuid>cf574e15-6512-4128-84bc-15785e462b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/static/media/carinsurance.c2dadb4c.svg 1x, /_next/static/media/carinsurance.c2dadb4c.svg 2x</value>
      <webElementGuid>d2b6cdac-2dc6-4407-a007-0a88b5f0be9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section-product-recommendations&quot;)/div[@class=&quot;px-4 sm:px-6 lg:px-8 xs:mt-96 md:mt-96&quot;]/div[@class=&quot;p-8 flex flex-col rounded-[45px] bg-brand-whitegray shadow-md&quot;]/div[@class=&quot;mt-6 w-full max-w-xl mx-auto grid grid-rows-3 sm:grid-rows-1 grid-cols-1 sm:grid-cols-2 gap-x-8 gap-y-5&quot;]/a[@class=&quot;link_base-link__fSADh inline-flex flex-col items-center text-gray-2 p-4 rounded-xl transition duration-500 ease-in-out hover:shadow-sm hover:bg-white&quot;]/div[@class=&quot;mb-2.5 relative&quot;]/div[@class=&quot;opacity-100&quot;]/span[1]/img[1]</value>
      <webElementGuid>b9268d29-a56a-45ea-ba64-7202bd90930d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section-product-recommendations']/div/div/div[2]/a[4]/div/div/span/img</value>
      <webElementGuid>8349d0e5-19ee-4e65-b8ce-0827f1173238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Asuransi Kendaraan']</value>
      <webElementGuid>aa77b56b-9764-483b-b74b-b4a5319bc030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/div/div/span/img</value>
      <webElementGuid>15bb5785-e185-42b1-af24-a1c27a494141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Asuransi Kendaraan' and @src = '/_next/static/media/carinsurance.c2dadb4c.svg']</value>
      <webElementGuid>8c4b95c8-eb74-47b4-9f65-76aa6422387d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
