<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Saya mengerti dan lanjutkan_terms-and_590fa3</name>
   <tag></tag>
   <elementGuidId>7bcbdaba-80a5-49a5-957e-741cde38160b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#terms-and-condition</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='terms-and-condition']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Saya mengerti dan lanjutkan&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15d37a2c-c1d6-4165-b537-f5008378d70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4738d75b-96e5-4289-82c1-92b369900e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>terms-and-condition</value>
      <webElementGuid>efddaa46-bc58-483e-94f4-4f2f54f6e240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>terms-and-condition</value>
      <webElementGuid>186b7e91-1b9d-4b18-a05b-ffe4f642a569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-8 w-8 rounded-lg border-2 border-brand-pink text-brand-pink focus:outlin-none focus:ring focus:ring-brand-highlight</value>
      <webElementGuid>011590a5-467d-471d-84ac-88454d0ce354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;terms-and-condition&quot;)</value>
      <webElementGuid>a7cd61b4-bb0f-4b7a-a859-8458d56bc959</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='terms-and-condition']</value>
      <webElementGuid>a7841bcc-1b14-47ab-bf20-28a31f536269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-12']/div[2]/section/div[3]/div/input</value>
      <webElementGuid>8d5cd21e-0f83-4054-b073-871248206afa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[3]/div/input</value>
      <webElementGuid>0a374711-896a-4c23-8aa7-752c2888a695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'terms-and-condition' and @name = 'terms-and-condition']</value>
      <webElementGuid>876c12c1-8156-488b-bb22-d8d6725beb35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
