<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__user_first_name</name>
   <tag></tag>
   <elementGuidId>7ca37d0e-5ca3-4fcb-8647-776439b82aa4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_first_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_first_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Contoh: John&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>06e03a9d-d8b3-4e2f-915b-b6e3c444239d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_first_name</value>
      <webElementGuid>baa77877-38b5-442f-9e13-e4b212840ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>843f7987-a59a-467a-862f-5656747af5d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_first_name</value>
      <webElementGuid>5741ec52-183f-4450-a21c-bf217ff3b182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: John</value>
      <webElementGuid>e82f266e-573f-431c-b79e-950c9bf63aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-field_field-input__Z28kU</value>
      <webElementGuid>b3d23f3f-207b-412c-afa9-ff227498d0db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>sena</value>
      <webElementGuid>5f82bc4f-6b23-48ac-81a0-56a6e6105d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_first_name&quot;)</value>
      <webElementGuid>88220f5a-422b-45cc-bc6e-af950fce5bf1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_first_name']</value>
      <webElementGuid>ab9f1e22-4c87-413a-9280-fd11822bb2a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking-form']/div/form/div[2]/div/div/div/input</value>
      <webElementGuid>9125c5f1-0e36-4d08-99b0-39cc7dbf4b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>41c82aba-65f5-4bb8-9c9c-510969505869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'user_first_name' and @type = 'text' and @name = 'user_first_name' and @placeholder = 'Contoh: John']</value>
      <webElementGuid>868d605a-1c17-4af0-8b36-25e6d2d047ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
