<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__vehicle_machine_number</name>
   <tag></tag>
   <elementGuidId>fa71ca42-39fe-45a1-803a-bf27a7edf0b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vehicle_machine_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vehicle_machine_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Contoh: DF8012342731&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0586987-ef0d-4017-a4e1-32448d171713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vehicle_machine_number</value>
      <webElementGuid>a62b0d5a-6d10-4450-ba7e-38d3e5ddf4b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0029a3f1-f66a-4233-b8a1-163f51e4dc9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vehicle_machine_number</value>
      <webElementGuid>7a74f2a4-d5e1-4e92-a7b8-b461639dfb45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: DF8012342731</value>
      <webElementGuid>908e9037-a47f-486b-a56b-56e9fd7a2f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-field_field-input__Z28kU</value>
      <webElementGuid>d17906d6-4d4e-413c-8192-53d3404fc0f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vehicle_machine_number&quot;)</value>
      <webElementGuid>e19ff244-c6f7-45d9-9c25-47fc24149f2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vehicle_machine_number']</value>
      <webElementGuid>6301f808-b490-44b2-8c2f-15c2c7f60abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/section/div[2]/div[3]/div/div[5]/div/div/input</value>
      <webElementGuid>46249173-5bae-4cbc-8b1a-8e555b13d57c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>a5c9fd59-8404-4d52-a0f3-c06a97e4237a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'vehicle_machine_number' and @type = 'text' and @name = 'vehicle_machine_number' and @placeholder = 'Contoh: DF8012342731']</value>
      <webElementGuid>378e1b9b-49cd-4783-bc90-3f1b57997c01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
