<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Aksesoris (opsional)_vehicle_acc_efcc37</name>
   <tag></tag>
   <elementGuidId>87736c17-aedd-485c-b4bb-262cbe54df84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vehicle_accessories_name1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vehicle_accessories_name1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Aksesoris 1&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56cf8abd-3bdc-4446-8571-e423897a41bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vehicle_accessories_name1</value>
      <webElementGuid>55143ab3-fcfa-4914-9620-a2d056e1c51d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0f27ebb9-d0d0-4b19-8b17-dc7ef05c9f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vehicle_accessories_name1</value>
      <webElementGuid>4335b191-e86c-4fcd-8b8b-e38aa1a5d203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Aksesoris 1</value>
      <webElementGuid>d8d45c60-47cb-4b50-acc1-089dda1101d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-field_field-input__Z28kU</value>
      <webElementGuid>cc99eea0-6f1f-4664-bbfc-131a6c3b8c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vehicle_accessories_name1&quot;)</value>
      <webElementGuid>0fd099b5-1c41-4cd9-a4f1-3a989861b411</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vehicle_accessories_name1']</value>
      <webElementGuid>9e72e94a-d8af-4077-b211-96c2ecb2acf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/section/div[2]/div[3]/div[3]/div/div/div/input</value>
      <webElementGuid>2fd75e32-acf1-4495-a01b-330a5634fdbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>6312c332-49dc-4bb3-bc1a-04a418bd44dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'vehicle_accessories_name1' and @type = 'text' and @name = 'vehicle_accessories_name1' and @placeholder = 'Aksesoris 1']</value>
      <webElementGuid>ab13333b-7a30-414d-95a6-a6eb34fd2446</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
