<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__user_birth_date</name>
   <tag></tag>
   <elementGuidId>9df136cd-c043-458a-8fea-8b64381555f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_birth_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_birth_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;DD/MM/YYYY&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75ffce4f-b51d-4a91-a14a-f7fdf24f94ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-field_field-input__Z28kU !rounded-r-none react-datepicker-ignore-onclickoutside</value>
      <webElementGuid>df58b6fd-9ede-4eea-b0df-4def372f87c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_birth_date</value>
      <webElementGuid>1bef2724-1479-4b8e-8ca9-6841516275fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_birth_date</value>
      <webElementGuid>7c81bd1b-f4c9-4a15-aef6-70007faa7a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD/MM/YYYY</value>
      <webElementGuid>4e6392dd-a73b-4763-9bdd-83e763d1fa71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>20/04/2000</value>
      <webElementGuid>323740d8-8f6b-4256-9cc6-5c46fb94e8c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_birth_date&quot;)</value>
      <webElementGuid>97fe6fc4-98e6-4f53-99d9-3bb65056c54c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_birth_date']</value>
      <webElementGuid>bdfbfc2f-e576-4129-bfa8-31f82cca3f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking-form']/div/form/div[2]/div/div[4]/div/div/div/input</value>
      <webElementGuid>b0ac4a8a-3c68-4a53-ac87-d65c240a072f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>ceac8121-27f6-471d-8f0d-9422f490f6d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'user_birth_date' and @name = 'user_birth_date' and @placeholder = 'DD/MM/YYYY']</value>
      <webElementGuid>ff8661e5-9b1d-407a-9ae2-a8eebedff5fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
