<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__vehicle_plat_number</name>
   <tag></tag>
   <elementGuidId>367840e6-18e2-458b-8f15-b9c9769ccdc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vehicle_plat_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vehicle_plat_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Contoh: B1234ABC&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc4f1475-3bb8-454c-af93-edfdfa9e568a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vehicle_plat_number</value>
      <webElementGuid>7696d434-76f6-44c8-93dc-a0d2e0c09096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6546adf6-e09f-42b0-b456-b0d2d2f82621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vehicle_plat_number</value>
      <webElementGuid>5092542c-ab4f-4b26-9095-3eaf29e61775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: B1234ABC</value>
      <webElementGuid>6fadb6a9-41fa-4318-9914-294467e99938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-field_field-input__Z28kU</value>
      <webElementGuid>49f36178-c707-4267-9ce6-325c5e28f212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>d9eec5af-ed11-4a5e-b13f-56e0bfc3cdfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vehicle_plat_number&quot;)</value>
      <webElementGuid>6670cab9-cda5-413b-985b-7f6375db372a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vehicle_plat_number']</value>
      <webElementGuid>1b5011cb-b2fa-4016-a5bd-5470e2f75165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/section/div[2]/div[3]/div/div[3]/div/div/input</value>
      <webElementGuid>b77eafde-b5a6-4e59-8d01-94a341452a89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div/div/input</value>
      <webElementGuid>25d4c4ea-8f52-4433-b0f1-bbe7843c9f99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'vehicle_plat_number' and @type = 'text' and @name = 'vehicle_plat_number' and @placeholder = 'Contoh: B1234ABC']</value>
      <webElementGuid>7daf751f-1d9b-4d95-984c-8ac103858080</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
