<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__user_last_name</name>
   <tag></tag>
   <elementGuidId>a837ce8e-e558-4e60-bcbc-4552cd2c2999</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_last_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_last_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Contoh: Doe&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>093682ad-2e3b-40ae-826e-21a2d3c18b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_last_name</value>
      <webElementGuid>661af7f5-7d50-4fa2-8d77-f83ed106751e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c57d9f39-1387-4a79-bd0e-ac40ab59ce2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_last_name</value>
      <webElementGuid>fb455bb7-5954-4cf2-8cdc-88646ba4c26e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: Doe</value>
      <webElementGuid>b418c1f7-1321-46bd-8c0a-5d02c0a8b865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-field_field-input__Z28kU</value>
      <webElementGuid>2572e8eb-e28e-4b1c-942e-3e9e61ef8af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>469361c2-2842-4bed-b27d-1d196ccc2422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_last_name&quot;)</value>
      <webElementGuid>5142ae4c-0fe9-4c38-8b59-44b75c75e853</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_last_name']</value>
      <webElementGuid>645e0fc4-7961-4e08-ab86-2eb0d6af034c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking-form']/div/form/div[2]/div/div[2]/div/input</value>
      <webElementGuid>4a0092bf-ef5f-47f7-9a37-847ce3445901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>f386d807-a57d-497a-a670-0af1dfbc8f7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'user_last_name' and @type = 'text' and @name = 'user_last_name' and @placeholder = 'Contoh: Doe']</value>
      <webElementGuid>d03e3a80-e033-44e6-9bd8-6532dfed2dbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
