<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_Client</name>
   <tag></tag>
   <elementGuidId>63652e77-93d0-428c-8200-346f5cf15d28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#section-clients</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='section-clients']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#section-clients</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>section</value>
      <webElementGuid>f1ef5390-bc8d-4dcf-9512-95bb3456f8ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>section-clients</value>
      <webElementGuid>75d88d96-bfaf-4617-bb67-7cc470746d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full h-full flex flex-col max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-5</value>
      <webElementGuid>0cd5a22a-71b7-44c7-aa53-1266a345f3b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Client</value>
      <webElementGuid>d50bd105-8f7c-4d1b-879f-ead03353cd31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section-clients&quot;)</value>
      <webElementGuid>3a96ec7f-286f-47aa-a26f-d71a2bc36d5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//section[@id='section-clients']</value>
      <webElementGuid>37e282c0-859b-4ea4-a5ae-61c36365c2ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[4]/section</value>
      <webElementGuid>53c686d4-8548-4eb2-8d4c-3f918facd8a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk Asuransi Lainnya'])[1]/following::section[1]</value>
      <webElementGuid>2c7d5866-2324-4d09-bbf4-1489951a5103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asuransi Kendaraan'])[1]/following::section[1]</value>
      <webElementGuid>35645029-85a0-413e-a9d7-84af22c35ebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kenapa Ezypolis?'])[1]/preceding::section[2]</value>
      <webElementGuid>0b1e5b82-d001-4634-a786-1be9e43a5769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section</value>
      <webElementGuid>be1a0854-807d-4c7b-88eb-ed50436f5221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[@id = 'section-clients' and (text() = 'Client' or . = 'Client')]</value>
      <webElementGuid>ad928c15-1ed3-4c17-865a-530e097bba42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
