<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_sena pahlevi</name>
   <tag></tag>
   <elementGuidId>40523303-a862-462b-a5d2-4de9bd30c91f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.font-bold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='headlessui-popover-button-1']/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Hi sena pahlevi&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>52499afa-8f76-4b6c-9dbd-606ac0d1587e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-bold</value>
      <webElementGuid>08626304-acca-4a42-84c8-d1ff782aa9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>sena pahlevi</value>
      <webElementGuid>8d0a54a4-25a8-4de8-9cf6-f4c36d1dd383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-popover-button-1&quot;)/span[@class=&quot;hidden lg:block&quot;]/span[@class=&quot;font-bold&quot;]</value>
      <webElementGuid>70cbdce6-26ed-4d2f-abab-72b8959dd875</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='headlessui-popover-button-1']/span/span</value>
      <webElementGuid>821acd85-da53-4ad9-b8f1-6d325b48d7f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang Kami'])[1]/following::span[2]</value>
      <webElementGuid>7e96f38c-710a-4d74-82b2-146f8889afc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/1'])[1]/preceding::span[2]</value>
      <webElementGuid>aa5061d4-96d7-40a4-83ab-39b1b5a1b097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rekomendasi Produk'])[1]/preceding::span[7]</value>
      <webElementGuid>63ce7457-ce58-4b7f-86a8-8fa79f927ed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='sena pahlevi']/parent::*</value>
      <webElementGuid>bb6102ad-4b2f-4c86-aee6-7d96b7fd3ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>bd66659d-1efe-42d9-a9c9-98f8bcfa573b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'sena pahlevi' or . = 'sena pahlevi')]</value>
      <webElementGuid>54048113-5583-4d3d-b610-680921fd7d76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
