<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Karir</name>
   <tag></tag>
   <elementGuidId>e2f30344-961a-4992-9810-6097d32650f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/footer/div[2]/div[2]/nav/ul/li[3]/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Karir&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ea2bff7c-a4fd-470c-8c37-cdfcc5a2578b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link_base-link__fSADh inline-flex text-sm text-gray-4</value>
      <webElementGuid>75dbdc9f-1f1a-4ed1-9ef0-41f682840dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/karir</value>
      <webElementGuid>306655e4-c994-4890-9608-75700b7ae8c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Karir</value>
      <webElementGuid>a28a6e53-5cd9-4960-9633-bc526e8fafec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen flex flex-col&quot;]/footer[@class=&quot;relative bg-brand-ivory mt-26&quot;]/div[@class=&quot;w-full max-w-8xl mx-auto flex flex-col space-y-4 py-5 px-4 sm:px-6 lg:px-8&quot;]/div[@class=&quot;flex flex-col lg:flex-row space-y-6 lg:space-y-0 lg:justify-between&quot;]/nav[1]/ul[@class=&quot;grid lg:grid-cols-4 gap-x-11 xs:grid-cols-2 gap-x-5&quot;]/li[3]/ul[@class=&quot;mt-3.5 space-y-1.5&quot;]/li[3]/a[@class=&quot;link_base-link__fSADh inline-flex text-sm text-gray-4&quot;]</value>
      <webElementGuid>441944ec-30a8-4d0b-978a-e6d6982841fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/footer/div[2]/div[2]/nav/ul/li[3]/ul/li[3]/a</value>
      <webElementGuid>b19d9ced-8480-4d23-87ea-5f7488d4faec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Karir')]</value>
      <webElementGuid>9b5678e6-cbbf-4e8a-abab-f72b506c9cdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tim Kami'])[1]/following::a[1]</value>
      <webElementGuid>0e1bc505-81fb-4735-aec3-340a8af71a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profil Perusahaan'])[1]/following::a[2]</value>
      <webElementGuid>938c59ff-e3cb-4212-bef2-909db6293457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kebijakan Privasi'])[1]/preceding::a[1]</value>
      <webElementGuid>d0643e6c-eb57-41a2-b4a4-728a1c26a8be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Syarat dan Ketentuan'])[1]/preceding::a[2]</value>
      <webElementGuid>91744879-c5eb-47c2-b830-e325857c288a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Karir']/parent::*</value>
      <webElementGuid>d75a94d3-6336-45e8-aa0e-6c51d0a24fd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/karir')]</value>
      <webElementGuid>50dee48f-7e01-4b7b-84de-065616ed555a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[3]/a</value>
      <webElementGuid>417b0e81-51bf-49db-85dd-de264fff3c0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/karir' and (text() = 'Karir' or . = 'Karir')]</value>
      <webElementGuid>3206228b-1923-4bfe-9c40-b12df927b1c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
