<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Semua</name>
   <tag></tag>
   <elementGuidId>0ca5d4e7-c4b8-402b-bea5-65567ea1314f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='job-opportunity']/section/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Semua$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ee69cb17-7235-4508-9137-ecd49173ce93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-white flex items-center border border-brand-darkpink text-brand-darkpink rounded-2xl py-1 px-3 shadow-lg w-4/5 md:w-1/5 cursor-pointer </value>
      <webElementGuid>ac0332e6-a71b-4f44-883d-c50ffb7cfc66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Semua</value>
      <webElementGuid>e5f78acd-0021-42e5-a206-abe34bca3504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;job-opportunity&quot;)/section[@class=&quot;w-full h-full flex flex-col max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-15&quot;]/div[@class=&quot;flex flex-col md:flex-row items-center mb-10 relative z-10&quot;]/div[@class=&quot;bg-white flex items-center border border-brand-darkpink text-brand-darkpink rounded-2xl py-1 px-3 shadow-lg w-4/5 md:w-1/5 cursor-pointer&quot;]</value>
      <webElementGuid>bb1df4fa-9808-430b-8a3e-79497f4b22e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='job-opportunity']/section/div/div</value>
      <webElementGuid>c3de5543-f011-4d35-bb0b-b1dab8933cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Posisi Tersedia'])[1]/following::div[1]</value>
      <webElementGuid>86d8a224-f496-41ce-b7c8-bf60f2606ce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#seEzyitu!'])[1]/following::div[3]</value>
      <webElementGuid>56589606-e85a-415e-8cb1-371e4c3f0522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lorem ipsum'])[1]/preceding::div[1]</value>
      <webElementGuid>d600d5d2-c68c-4014-9bf8-2872533bc6e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lamar Sekarang'])[1]/preceding::div[2]</value>
      <webElementGuid>fdffcd2e-891a-44c8-ba43-557ff297e340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div</value>
      <webElementGuid>8ec94a6a-bd78-4b77-8cee-6f33f24b9b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Semua' or . = 'Semua')]</value>
      <webElementGuid>aee28802-43d9-4507-8fd4-3f132a4b8a28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
