<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>8a1ab161-a010-4f8c-a197-1e85f2ef6f14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search-banner']/div/section/div/form/button/div/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.bg-brand-pink.rounded-full.flex.justify-center.items-center.p-1 > span > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#search-banner >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6bbb1f21-6324-46a5-bc5d-9b69dbd85389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/static/media/Arrow_right.db56b955.svg</value>
      <webElementGuid>d66afce2-162d-461d-a26d-687726bfaa3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>50197cd1-5899-4580-90ab-67f5953d5979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>intrinsic</value>
      <webElementGuid>864e5aac-a08d-4d84-965c-739611d2309a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/static/media/Arrow_right.db56b955.svg 1x, /_next/static/media/Arrow_right.db56b955.svg 2x</value>
      <webElementGuid>f8745a38-283f-44e7-b23b-a5b048c003c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-banner&quot;)/div[@class=&quot;relative h-96&quot;]/section[@class=&quot;w-full h-full flex flex-col max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-15&quot;]/div[@class=&quot;relative z-10&quot;]/form[@class=&quot;flex items-center bg-white rounded-3xl px-3 w-full md:w-1/2&quot;]/button[1]/div[@class=&quot;bg-brand-pink rounded-full flex justify-center items-center p-1&quot;]/span[1]/img[1]</value>
      <webElementGuid>9b5fda13-a7e4-48ad-a35e-c4bd12eb5bf5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-banner']/div/section/div/form/button/div/span/img</value>
      <webElementGuid>c2d69aa6-7621-4a0f-81b0-ffc01234f92f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/span/img</value>
      <webElementGuid>304502ef-6c3f-483b-bcee-f38302549796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/_next/static/media/Arrow_right.db56b955.svg']</value>
      <webElementGuid>31bfc7c5-d99c-416c-a596-753a0e4aee87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
