<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_seEzyitu_jobtitle</name>
   <tag></tag>
   <elementGuidId>c3aa61a2-b5b7-4a25-97d8-f9aa7c5a003a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='jobtitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;jobtitle&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Nama Pekerjaan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0309d833-bc46-48e5-bd7e-8a6170ab913e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2255a534-ae68-4fde-9f32-4819086e5184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jobtitle</value>
      <webElementGuid>63fbf69e-9e53-490c-a038-0d416b5a2216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Pekerjaan</value>
      <webElementGuid>6d3714e2-eab1-43f5-a5ca-f02a6685e274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full border-transparent focus:border-transparent focus:ring-0</value>
      <webElementGuid>9e83156a-0a32-4eb9-9fb5-e859a3ca6b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-banner&quot;)/div[@class=&quot;relative h-96&quot;]/section[@class=&quot;w-full h-full flex flex-col max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-15&quot;]/div[@class=&quot;relative z-10&quot;]/form[@class=&quot;flex items-center bg-white rounded-3xl px-3 w-full md:w-1/2&quot;]/input[@class=&quot;w-full border-transparent focus:border-transparent focus:ring-0&quot;]</value>
      <webElementGuid>a8046a6f-c3f4-4dd7-ad77-500b0ace91df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='jobtitle']</value>
      <webElementGuid>15188356-e47d-4815-98ba-b49e2cc7e057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-banner']/div/section/div/form/input</value>
      <webElementGuid>73f7d1c3-3e1f-48e8-819c-0cbb095b3b00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>395d3a49-d91d-4880-8f79-e7bb6b10707d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'jobtitle' and @placeholder = 'Nama Pekerjaan']</value>
      <webElementGuid>421d8cfe-9724-477b-9141-a30d1630e579</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
