<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Marketing</name>
   <tag></tag>
   <elementGuidId>ebffa15e-64f0-47cd-8898-23f356e14654</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='job-opportunity']/section/div/div[2]/ul/li[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.jobopportunity_green__MFa_Y</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Marketing&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>1005cc58-9882-43d5-a610-4d0fec90a4b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jobopportunity_green__MFa_Y</value>
      <webElementGuid>9442c95f-e2d8-4c7f-9aea-dd6202728c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Marketing</value>
      <webElementGuid>12acdcbe-50c5-4483-8140-91e0be14fc04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;job-opportunity&quot;)/section[@class=&quot;w-full h-full flex flex-col max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-15&quot;]/div[@class=&quot;flex flex-col md:flex-row items-center mb-10 relative z-10&quot;]/div[@class=&quot;absolute bg-white inset-x-auto md:right-0 top-full md:top-3/4 mt-2 border border-brand-darkpink text-brand-darkpink rounded-2xl py-1 px-3 shadow-lg w-4/5 md:w-1/5&quot;]/ul[@class=&quot;jobopportunity_department__7MTtJ&quot;]/li[@class=&quot;jobopportunity_green__MFa_Y&quot;]</value>
      <webElementGuid>87216ac3-463b-4705-9d05-9dce976654e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='job-opportunity']/section/div/div[2]/ul/li[3]</value>
      <webElementGuid>6af7867a-3c9b-4ee9-aec4-bf915ad5b64d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Claims'])[1]/following::li[1]</value>
      <webElementGuid>ec064bb9-ca40-4a62-8eee-578fab20828a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua'])[2]/following::li[2]</value>
      <webElementGuid>ebbfcd9a-d5c2-4e4c-b419-bd53c01f3d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IT'])[1]/preceding::li[1]</value>
      <webElementGuid>cdad42d4-1c39-427b-8350-1141ea2f8e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lorem ipsum'])[1]/preceding::li[2]</value>
      <webElementGuid>528dc2a9-d787-4161-b725-1d4e9c7b78b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Marketing']/parent::*</value>
      <webElementGuid>98281210-8288-49ae-b1f8-ee960136afec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[3]</value>
      <webElementGuid>7aa29129-c07d-4e3c-93e3-7a9eaaf54eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Marketing' or . = 'Marketing')]</value>
      <webElementGuid>cb02a75d-4567-4566-a3a2-8aa74f5aaa17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
