<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Masuk</name>
   <tag></tag>
   <elementGuidId>f2507350-9369-4125-a4b7-2b8df82542d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/header/div[2]/nav[2]/ul/li/a/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Masuk&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2b7965d6-303a-4be8-bfd8-d5ba6d7ac12b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link_base-link__fSADh relative px-1 py-2 inline-flex text-sm text-gray-3 hover:text-gray-2</value>
      <webElementGuid>4ae866e3-bf86-4545-87d3-4ab78c618447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>776c5484-b7bf-49a2-b7fd-5b82a8fb93a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen flex flex-col&quot;]/header[@class=&quot;layout_header__VsoJR&quot;]/div[@class=&quot;max-w-8xl h-[58px] mx-auto flex items-center justify-between px-4 sm:px-6 lg:px-8 relative&quot;]/nav[2]/ul[@class=&quot;-mx-1&quot;]/li[1]/a[1]/a[@class=&quot;link_base-link__fSADh relative px-1 py-2 inline-flex text-sm text-gray-3 hover:text-gray-2&quot;]</value>
      <webElementGuid>f81777d3-2915-41c7-a133-83673f55293f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/header/div[2]/nav[2]/ul/li/a/a</value>
      <webElementGuid>dd1effea-1d79-411b-b23e-0d334d8a4904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Masuk')]</value>
      <webElementGuid>99299c35-cc89-4519-bfb1-f41bb7456c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang Kami'])[1]/following::a[2]</value>
      <webElementGuid>336c260a-63c8-40a1-9206-ee9aab5cf6ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bantuan'])[1]/following::a[2]</value>
      <webElementGuid>9a3c4d48-ac2e-42a9-b098-957a766f14a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/2'])[1]/preceding::a[1]</value>
      <webElementGuid>8ed3f7d3-986c-4ad8-be61-ffba04a353c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Sekarang'])[1]/preceding::a[1]</value>
      <webElementGuid>99b5da40-73e0-4b3a-87ac-43bf96878fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Masuk']/parent::*</value>
      <webElementGuid>1d2ffe09-e43e-49f1-a2ed-e8e8e45f5f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav[2]/ul/li/a/a</value>
      <webElementGuid>267076a3-15fe-4295-9ea3-ad191074f703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>dae21b22-8ec5-4b30-a547-f93373ed5707</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
