<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Virtual_Account_Numb_Salin</name>
   <tag></tag>
   <elementGuidId>64266e48-6567-491f-964a-7f5b4dbb6753</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;application&quot;]/div/div/div[1]/div[3]/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.float-right.clickable.copy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Salin&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f82af32b-829f-42f4-8d7e-ac7a1e5fb870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>float-right clickable copy</value>
      <webElementGuid>63256a86-e0c7-4087-9843-54b41f68b0f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Salin</value>
      <webElementGuid>61e0f416-0bed-4b3a-b886-f01fbde68cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application&quot;)/div[@class=&quot;page-container scroll&quot;]/div[@class=&quot;payment-page&quot;]/div[1]/div[@class=&quot;payment-page-layout payment-page-text&quot;]/div[2]/div[@class=&quot;float-right clickable copy&quot;]</value>
      <webElementGuid>1def5d92-4f3d-4c72-b846-499e0319cc63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Personal Accident/User Journey Purchase PA - Login/iframe_Syarat dan Ketentuan_popup_1713947298114</value>
      <webElementGuid>d5e10dba-a4d9-4189-9215-931b8dce09ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application']/div/div/div/div[3]/div[2]/div[2]</value>
      <webElementGuid>3aee96c8-603f-41ae-8830-16130a036aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor virtual account'])[1]/following::div[3]</value>
      <webElementGuid>c6b1f8c9-fc73-44ba-ab81-75bfef430d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lakukan pembayaran dari rekening bank BCA ke nomor virtual account berikut.'])[1]/following::div[5]</value>
      <webElementGuid>6b7299d9-cba6-4540-ac1a-8b6437eb7bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cara bayar'])[1]/preceding::div[1]</value>
      <webElementGuid>aa2cf5a3-d3e1-4151-a208-226e32a1976f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ATM BCA'])[1]/preceding::div[3]</value>
      <webElementGuid>7ce61059-1db4-4a5a-a97d-94e6786f4be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Salin']/parent::*</value>
      <webElementGuid>3da79d3c-7600-4c8a-ab2e-e15c74cc5201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>bb464f36-bd9c-4631-801b-1889256acd28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Salin' or . = 'Salin')]</value>
      <webElementGuid>9ba3d601-7863-46d9-8030-510604ddbdb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
