<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pembayaran berhasilRp75.000Order ID pay_9dd434</name>
   <tag></tag>
   <elementGuidId>61480194-af98-420d-b6f9-c04c0cf54f84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='application']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.success-wrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=&quot;Pembayaran berhasilRp75.000Order ID #pay2024421881&quot;i >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9640bc79-7e9b-4c67-b947-abe4c9a951cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>success-wrapper</value>
      <webElementGuid>11812af0-045d-498e-ba3f-09089dedd79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pembayaran berhasilRp75.000Order ID #pay2024421881</value>
      <webElementGuid>541eba34-161f-4c8e-876f-872698498584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application&quot;)/div[@class=&quot;fullscreen-container&quot;]/div[@class=&quot;success-wrapper&quot;]</value>
      <webElementGuid>063fb639-0bf6-4949-8fa1-ba64c6989d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Personal Accident/User Journey Purchase PA - Login/iframe_concat(id(, , snap-midtrans, , ))_po_6b00ce</value>
      <webElementGuid>a68cf8f3-1e4f-4e87-b1ae-65c1092935ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application']/div/div</value>
      <webElementGuid>9fbe4250-8ff9-4de0-9746-648985667097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>74df0813-7251-4e3f-8ddb-004d2c53d149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Pembayaran berhasilRp75.000Order ID #pay2024421881' or . = 'Pembayaran berhasilRp75.000Order ID #pay2024421881')]</value>
      <webElementGuid>2a4b0c48-b74e-43dd-a65c-bae631662f19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
