<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Indonesia</name>
   <tag></tag>
   <elementGuidId>7846c9d9-1114-48d6-9741-d0dcb2023838</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-user_citizenship-option-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-user_citizenship-option-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Indonesia&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0a93729d-3315-4768-894c-e27abd373414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-select__option react-select__option--is-focused css-1n7v3ny-option</value>
      <webElementGuid>e4ab2b2b-7061-474e-8b97-a4875268490d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-user_citizenship-option-0</value>
      <webElementGuid>877ba47b-0d0a-41fa-b856-b191eb1db16e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>14db696a-8f74-4a24-b063-d5072718e5c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Indonesia</value>
      <webElementGuid>eb082b0f-d776-4225-999e-d6a4ceecd2f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-user_citizenship-option-0&quot;)</value>
      <webElementGuid>adefdad8-82a6-40bf-afff-be13107eec6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-user_citizenship-option-0']</value>
      <webElementGuid>fd5d7db6-c45d-432f-a9fd-8949427d5b3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking-form']/div/form/div[2]/div/div[6]/div/div/div[2]/div/div</value>
      <webElementGuid>33993b02-44a8-4e60-b8ce-96907940c392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Kewarganegaraan'])[1]/following::div[5]</value>
      <webElementGuid>f92d60a5-a521-4f53-996a-ae150b3ae615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asing'])[1]/preceding::div[1]</value>
      <webElementGuid>561906cb-3807-49c4-b6c9-134e0297a8a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Indonesia']/parent::*</value>
      <webElementGuid>ab7d32f9-27e7-450e-bfde-69c033387840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div</value>
      <webElementGuid>55e1b359-5530-4b95-921c-eab43ff22ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-user_citizenship-option-0' and (text() = 'Indonesia' or . = 'Indonesia')]</value>
      <webElementGuid>4ca02109-a649-476f-a4ba-bed6227a1ec9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
