<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select_Virtual_Account_BCA</name>
   <tag></tag>
   <elementGuidId>6b699803-1ede-443a-85ce-47804dd37a81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;application&quot;]/div/div/div[3]/div[1]/div/div[2]/div/a[1]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.float-right.clickable.copy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Salin&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>63f31547-d38f-4102-9711-4722c4c65690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>float-right clickable copy</value>
      <webElementGuid>e4684f06-e79d-4038-b864-5ff40b44126b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Salin</value>
      <webElementGuid>04bb77bb-0ff8-4130-9f7c-c6df413cf50a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application&quot;)/div[@class=&quot;page-container scroll&quot;]/div[@class=&quot;payment-page&quot;]/div[1]/div[@class=&quot;payment-page-layout payment-page-text&quot;]/div[2]/div[@class=&quot;float-right clickable copy&quot;]</value>
      <webElementGuid>18b7a32e-8da2-453f-a5c7-53b01965a827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Personal Accident/User Journey Purchase PA - Login/iframe_Syarat dan Ketentuan_popup_1713947298114</value>
      <webElementGuid>f52cba2e-7713-4e08-9d22-61a00a1a2882</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application']/div/div/div/div[3]/div[2]/div[2]</value>
      <webElementGuid>e7d123dc-fb9d-48ee-ab4e-2209a297e068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor virtual account'])[1]/following::div[3]</value>
      <webElementGuid>2dab4f33-64e0-4bf4-9be1-4874ecc22e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lakukan pembayaran dari rekening bank BCA ke nomor virtual account berikut.'])[1]/following::div[5]</value>
      <webElementGuid>1f5b8440-0a63-4bc2-ab51-011e543c2b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cara bayar'])[1]/preceding::div[1]</value>
      <webElementGuid>107996bc-091c-48e7-9269-7993831ddc70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ATM BCA'])[1]/preceding::div[3]</value>
      <webElementGuid>ce66876d-42f0-4ef5-81e5-9da1e37e97dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Salin']/parent::*</value>
      <webElementGuid>090be1a8-e676-4ec1-bc8f-d2a9d230d377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>683ede35-c79a-47db-be16-9681794cebd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Salin' or . = 'Salin')]</value>
      <webElementGuid>fc5328ba-fbf4-4261-9fcc-c87bf6c53e49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
