<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Salin</name>
   <tag></tag>
   <elementGuidId>c97cfd0a-d0a1-456e-9ebc-8c2105a20903</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.float-right.clickable.copy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='application']/div/div/div/div[3]/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Salin&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5f46b577-0f32-4161-b99e-27043afd9141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>float-right clickable copy</value>
      <webElementGuid>5563213f-0fd7-4407-a659-8efc23a78234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Salin</value>
      <webElementGuid>2d3e2734-bc09-4703-8349-962e49a4f72e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application&quot;)/div[@class=&quot;page-container scroll&quot;]/div[@class=&quot;payment-page&quot;]/div[1]/div[@class=&quot;payment-page-layout payment-page-text&quot;]/div[2]/div[@class=&quot;float-right clickable copy&quot;]</value>
      <webElementGuid>2b924e91-6194-483d-9d51-b5a5745634cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Personal Accident/User Journey Purchase PA - Login/iframe_Syarat dan Ketentuan_popup_1713947298114</value>
      <webElementGuid>354f49ca-5147-4202-8f8b-dbd0bd438897</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application']/div/div/div/div[3]/div[2]/div[2]</value>
      <webElementGuid>d46c9057-e983-41eb-a87b-ee418cd9814e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor virtual account'])[1]/following::div[3]</value>
      <webElementGuid>e274639a-57f2-4c17-947e-59ca4c9e1ec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lakukan pembayaran dari rekening bank BCA ke nomor virtual account berikut.'])[1]/following::div[5]</value>
      <webElementGuid>acc0277b-fae6-4b86-b6b5-7fe68fed62e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cara bayar'])[1]/preceding::div[1]</value>
      <webElementGuid>374fd9dc-9d9d-4125-8331-458686f7a133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ATM BCA'])[1]/preceding::div[3]</value>
      <webElementGuid>fc09d1b8-3d2f-4be8-90c6-b89153379bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Salin']/parent::*</value>
      <webElementGuid>439b8f52-c06f-48b4-ad81-fefd5692357d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>7dabaccf-e1e9-4b39-a160-33b9bccb7c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Salin' or . = 'Salin')]</value>
      <webElementGuid>57e8e983-2282-4ea0-8fae-126297403538</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
