<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__user_identity_num</name>
   <tag></tag>
   <elementGuidId>fbf8e16d-e09a-4907-978e-685c3395cebb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_identity_num</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_identity_num']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Contoh: 1233334333&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6933463d-f15f-4302-8468-7a0f19576d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_identity_num</value>
      <webElementGuid>abfd48c0-220e-4fa5-88ac-a43c87426891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d0ea2cb7-967b-4a7e-891e-87702b9f4a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_identity_num</value>
      <webElementGuid>224e8017-3ed7-4068-894f-b6e209b5b7bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: 1233334333</value>
      <webElementGuid>dffa0e23-d483-4302-9490-e8fddfe766eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-field_field-input__Z28kU</value>
      <webElementGuid>6ba18714-f5a9-4180-9024-10dc1b78c683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>be09a135-86ba-45b1-9db2-860015c6e043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>12a3bb8c-e414-4bdb-8c7f-29a8652f2e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_identity_num&quot;)</value>
      <webElementGuid>c238e01e-7c53-4c3d-a3b3-b25228072794</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_identity_num']</value>
      <webElementGuid>67d6a7c2-a17f-4294-bfae-c93f4a2d18a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking-form']/div/form/div[2]/div/div[14]/div/input</value>
      <webElementGuid>2afa7188-5c82-4b8e-ad74-30ec005092df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/input</value>
      <webElementGuid>43963370-3ad3-4301-bf3e-ec185e71029e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'user_identity_num' and @type = 'text' and @name = 'user_identity_num' and @placeholder = 'Contoh: 1233334333']</value>
      <webElementGuid>5aeb9097-5bed-4b95-8abb-5b57317d0eac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
