<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__user_identity_num</name>
   <tag></tag>
   <elementGuidId>fbf8e16d-e09a-4907-978e-685c3395cebb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_identity_num</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_identity_num']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Contoh: 1233334333&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>669f58db-ed10-43d3-959a-7da324d36207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_identity_num</value>
      <webElementGuid>74c9191c-9b3c-4c9e-bfb4-1006786e7c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7b8ce128-be26-49ee-833c-325af7db7c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_identity_num</value>
      <webElementGuid>c1be5338-937d-4966-b320-8a56d3be6ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: 1233334333</value>
      <webElementGuid>ba854afe-57fc-4fd2-97cc-8ff5887ff9f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-field_field-input__Z28kU</value>
      <webElementGuid>d7a8906e-9d46-4a97-b318-1aa8826a6b98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>2d45824f-cf06-45be-b24b-61b1f637b5d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>6245a940-34d1-436a-8cbd-4083373a18bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_identity_num&quot;)</value>
      <webElementGuid>42eccfd7-bb39-45ab-8d4d-551eded3b6fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_identity_num']</value>
      <webElementGuid>db60e041-f22c-4f01-af17-228054822bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking-form']/div/form/div[2]/div/div[14]/div/input</value>
      <webElementGuid>cc9188f4-bac0-4515-ba9e-187599a223e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/input</value>
      <webElementGuid>0dea2fa7-e9d4-4873-8d54-6776a9c24743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'user_identity_num' and @type = 'text' and @name = 'user_identity_num' and @placeholder = 'Contoh: 1233334333']</value>
      <webElementGuid>39701868-cc61-4423-9ee3-479ff7776e07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
