<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__hometown</name>
   <tag></tag>
   <elementGuidId>4f921a31-50d8-4427-b9aa-65d54dc3e5c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hometown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='hometown']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Contoh: Balikpapan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0d8c33d-d7bf-4e49-a347-222e03b3edc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hometown</value>
      <webElementGuid>948e1205-7f64-4dda-be61-2295dde5899f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5d45e487-bc8e-4113-90f1-f40d8114db1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hometown</value>
      <webElementGuid>276ca820-b78a-4bc2-b748-e91a78c3a716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: Balikpapan</value>
      <webElementGuid>dc8ad4d4-1c48-4e7f-9d5f-feec6eaf11d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-field_field-input__Z28kU</value>
      <webElementGuid>f9b714e9-d949-4a65-8011-ce306960f7d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hometown&quot;)</value>
      <webElementGuid>1ff683b8-282d-4dfc-9a73-643c320bfc8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>B</value>
      <webElementGuid>c26d848e-fc49-4a60-bb05-68dcecbb4c2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='hometown']</value>
      <webElementGuid>2635b71f-e8c1-4389-9729-543d9688708d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/section/div[2]/div/div/div/div[3]/div/div/input</value>
      <webElementGuid>684bb37c-bf3b-404e-a0ef-5980c1bf93c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>e8269037-be12-41e6-87c8-6a015e90cc8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'hometown' and @type = 'text' and @name = 'hometown' and @placeholder = 'Contoh: Balikpapan']</value>
      <webElementGuid>d54b901f-3adb-49cd-b5a6-089a59e6aaca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
