<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__user_birth_date</name>
   <tag></tag>
   <elementGuidId>c48c8136-02b2-4c1c-adaa-1495c6643584</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_birth_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_birth_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;DD/MM/YYYY&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e0c19f1-cb6a-45f0-992f-673f958c11fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-field_field-input__Z28kU !rounded-r-none react-datepicker-ignore-onclickoutside</value>
      <webElementGuid>7ea165fb-fcb1-4447-ab7e-d21172aeff31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_birth_date</value>
      <webElementGuid>290af0c4-310b-493e-80ca-c579143758b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_birth_date</value>
      <webElementGuid>cc3f84b0-9b25-4062-a570-2e36bb4c8dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD/MM/YYYY</value>
      <webElementGuid>89a629b5-8973-4ef2-a9fb-e95c76c6b0dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>20/04/2000</value>
      <webElementGuid>2192b863-ba0f-4c68-a957-f1620f3f45f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_birth_date&quot;)</value>
      <webElementGuid>30ddfe68-33bd-41e8-abc1-da6fa58fbd90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_birth_date']</value>
      <webElementGuid>0fcbb157-e5fe-468c-91f4-78a7cfcf4c5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking-form']/div/form/div[2]/div/div[4]/div/div/div/input</value>
      <webElementGuid>22a0c155-68a1-4e03-8c9c-34232a6148c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>2f38c23e-c434-4798-a6da-e0144720c072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'user_birth_date' and @name = 'user_birth_date' and @placeholder = 'DD/MM/YYYY']</value>
      <webElementGuid>9d482456-80f5-4a27-8299-7bed5891e1d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
