<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__hometown</name>
   <tag></tag>
   <elementGuidId>4f921a31-50d8-4427-b9aa-65d54dc3e5c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hometown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='hometown']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Contoh: Balikpapan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>795c7b83-1f1b-44a4-9324-47e7f0abd5d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hometown</value>
      <webElementGuid>fded7dd7-a596-40b3-bd0c-cc6f62a5a220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>82d445cc-b302-4f8a-8954-208bf23ab004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hometown</value>
      <webElementGuid>19843c6e-8ae0-45e2-b74f-5eab21cf2da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: Balikpapan</value>
      <webElementGuid>4b10f196-b636-4be4-9608-85e61681606c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-field_field-input__Z28kU</value>
      <webElementGuid>8fef6726-5444-4ece-b03c-c89546a26f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hometown&quot;)</value>
      <webElementGuid>bba74825-aa13-4ef7-988e-a56395ebb46d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>T</value>
      <webElementGuid>20fd97a3-c0ee-4700-bb76-7193c28e061b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='hometown']</value>
      <webElementGuid>00ba1ad0-a643-43d6-8c60-d61e2acef503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/section/div[2]/div/div/div/div[3]/div/div/input</value>
      <webElementGuid>2e083dcc-c1ea-4bb4-94f6-3b5bf1f29f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>f2c1dc7f-3950-45ce-807a-7dc30aed9834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'hometown' and @type = 'text' and @name = 'hometown' and @placeholder = 'Contoh: Balikpapan']</value>
      <webElementGuid>98bb2f97-6a91-46c6-9320-f5eaf4d4a4cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
