<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__user_birth_place</name>
   <tag></tag>
   <elementGuidId>3e24b5e6-c766-4d99-9f2a-b04674768b8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_birth_place</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_birth_place']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Contoh: Jakarta&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>759c1457-6c48-49ba-ad16-2df4bfa8f91c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_birth_place</value>
      <webElementGuid>28c41266-d8ba-474a-a153-5ae97ece9122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a70f6cdf-4fbd-4382-ade6-719ef219b34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_birth_place</value>
      <webElementGuid>668b2790-7c64-4584-bbf2-35c178c2bd2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: Jakarta</value>
      <webElementGuid>a2a4681c-9fa9-419a-a8b6-51982026196c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-field_field-input__Z28kU</value>
      <webElementGuid>4bf10056-18a7-488e-9e0e-8895d2cc19ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_birth_place&quot;)</value>
      <webElementGuid>f84f4b50-f87e-4f57-8172-84001dd5fb28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_birth_place']</value>
      <webElementGuid>693a2c5c-3ef2-4248-aa14-122361d573ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking-form']/div/form/div[2]/div/div[3]/div/input</value>
      <webElementGuid>e9386be4-0085-4cad-810c-794b7401bdac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>2eaf8a0f-6c5d-4fea-ac46-77a790b7a76b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'user_birth_place' and @type = 'text' and @name = 'user_birth_place' and @placeholder = 'Contoh: Jakarta']</value>
      <webElementGuid>07b279f7-285c-44f9-b06b-cc540ebe9b6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
