<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_75.000IDR</name>
   <tag></tag>
   <elementGuidId>7ef675cf-cac2-4c5d-b3e7-1f0b28193449</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.text-sm.text-right.text-gray-2.font-bold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='booking-form']/div[2]/div/div[3]/div/p[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;75.000IDR&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d3062fbb-e519-4c5c-9869-6cba1f7e1875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm text-right text-gray-2 font-bold</value>
      <webElementGuid>9b11f0e5-34d8-46bb-b7bb-b0e059ce5cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>75.000IDR</value>
      <webElementGuid>3f0cd802-b88a-4554-a450-01703a737581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;booking-form&quot;)/div[@class=&quot;ml-10 w-full max-w-[357px]&quot;]/div[@class=&quot;bg-white w-full rounded-t overflow-hidden&quot;]/div[@class=&quot;mx-3 mb-3 py-3.5 bg-brand-ivory&quot;]/div[@class=&quot;-mx-3 px-5 flex justify-between space-x-5&quot;]/p[@class=&quot;text-sm text-right text-gray-2 font-bold&quot;]</value>
      <webElementGuid>dff100f4-c773-4a29-9027-b7757ca009df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='booking-form']/div[2]/div/div[3]/div/p[2]</value>
      <webElementGuid>3e38a346-7edb-4cda-aed9-09cc0fb81f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Polis Selesai'])[1]/following::p[2]</value>
      <webElementGuid>a1c87a61-c022-4d9d-a39e-9bd4d9e984cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Polis Mulai Aktif'])[1]/following::p[2]</value>
      <webElementGuid>7fbf6533-4d59-4f26-bc54-1d0b6c0c0284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Footer'])[1]/preceding::p[1]</value>
      <webElementGuid>c74ddc96-0368-4488-81e2-a13f5b0aae2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='75.000']/parent::*</value>
      <webElementGuid>dc5c27da-ffc2-4685-a138-9e55bfe5704c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>1990c5c9-4958-48a5-825a-5985df80371b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '75.000IDR' or . = '75.000IDR')]</value>
      <webElementGuid>922a7f25-954e-439b-969c-9e6ca2cb6ce3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
