<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path</name>
   <tag></tag>
   <elementGuidId>fe616229-8f8c-451f-9870-1bfb1ba63449</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#headlessui-popover-button-7</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>be8bd599-d370-4dcc-bb5f-13e386eb1cdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill-rule</name>
      <type>Main</type>
      <value>evenodd</value>
      <webElementGuid>002b8366-7dc5-4bb2-af00-4bd9a45535cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z</value>
      <webElementGuid>7d999f4f-8de1-4180-9853-6f012e085b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clip-rule</name>
      <type>Main</type>
      <value>evenodd</value>
      <webElementGuid>80c0652f-4f71-4b42-a14f-aa33fb1dbe27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-popover-button-7&quot;)/svg[@class=&quot;h-5 w-5 block lg:hidden&quot;]/path[1]</value>
      <webElementGuid>bc89a84b-f2b8-451f-a1ab-7f43cd5a9e29</webElementGuid>
   </webElementProperties>
</WebElementEntity>
